//==================================================
// This file contains the Excluded objects
// Generated By User: abaranw2
// Format Version: 2
// Date: Thu Apr 30 19:13:22 2026
// ExclMode: default
//==================================================
CHECKSUM: "1534125422 1275491830"
MODULE: verichip7
Toggle version_reg [14] "logic version_reg[15:0]"
Toggle version_reg [0] "logic version_reg[15:0]"
Toggle version_reg [1] "logic version_reg[15:0]"
Toggle version_reg [2] "logic version_reg[15:0]"
Toggle version_reg [3] "logic version_reg[15:0]"
Toggle version_reg [4] "logic version_reg[15:0]"
Toggle version_reg [5] "logic version_reg[15:0]"
Toggle version_reg [6] "logic version_reg[15:0]"
Toggle version_reg [7] "logic version_reg[15:0]"
Toggle version_reg [8] "logic version_reg[15:0]"
Toggle version_reg [9] "logic version_reg[15:0]"
Toggle version_reg [10] "logic version_reg[15:0]"
Toggle version_reg [11] "logic version_reg[15:0]"
Toggle version_reg [12] "logic version_reg[15:0]"
Toggle version_reg [13] "logic version_reg[15:0]"
Toggle status_reg [7] "logic status_reg[15:0]"
Toggle status_reg [10] "logic status_reg[15:0]"
Toggle status_reg [11] "logic status_reg[15:0]"
Toggle status_reg [12] "logic status_reg[15:0]"
Toggle status_reg [13] "logic status_reg[15:0]"
Toggle status_reg [14] "logic status_reg[15:0]"
Toggle status_reg [15] "logic status_reg[15:0]"
Toggle status_reg [4] "logic status_reg[15:0]"
Toggle status_reg [5] "logic status_reg[15:0]"
Toggle status_reg [6] "logic status_reg[15:0]"
Toggle cmd_reg [14] "logic cmd_reg[15:0]"
Toggle cmd_reg [4] "logic cmd_reg[15:0]"
Toggle cmd_reg [5] "logic cmd_reg[15:0]"
Toggle cmd_reg [6] "logic cmd_reg[15:0]"
Toggle cmd_reg [7] "logic cmd_reg[15:0]"
Toggle cmd_reg [8] "logic cmd_reg[15:0]"
Toggle cmd_reg [9] "logic cmd_reg[15:0]"
Toggle cmd_reg [10] "logic cmd_reg[15:0]"
Toggle cmd_reg [11] "logic cmd_reg[15:0]"
Toggle cmd_reg [12] "logic cmd_reg[15:0]"
Toggle cmd_reg [13] "logic cmd_reg[15:0]"
Toggle con_reg [15] "logic con_reg[15:0]"
Toggle con_reg [0] "logic con_reg[15:0]"
Toggle con_reg [1] "logic con_reg[15:0]"
Toggle con_reg [2] "logic con_reg[15:0]"
Toggle con_reg [3] "logic con_reg[15:0]"
Toggle con_reg [4] "logic con_reg[15:0]"
Toggle con_reg [5] "logic con_reg[15:0]"
Toggle con_reg [6] "logic con_reg[15:0]"
Toggle con_reg [7] "logic con_reg[15:0]"
Toggle con_reg [10] "logic con_reg[15:0]"
Toggle con_reg [11] "logic con_reg[15:0]"
Toggle con_reg [12] "logic con_reg[15:0]"
Toggle con_reg [13] "logic con_reg[15:0]"
Toggle con_reg [14] "logic con_reg[15:0]"
CHECKSUM: "1534125422 1950314578"
INSTANCE: top_verichip7.verichip7
Condition 6 "3234656806" "(int1_en && (state == VCHIP_STATE_NORM) && valid && (bad_cmd || overflow)) 1 -1" (3 "1101")
Condition 3 "3660651549" "(valid && (bad_cmd || overflow)) 1 -1" (1 "01")
Condition 2 "385516972" "(export_dis && valid && bad_exp_cmd) 1 -1" (2 "101")
Condition 2 "385516972" "(export_dis && valid && bad_exp_cmd) 1 -1" (1 "011")
Condition 9 "3332304751" "(int2_en && (state == VCHIP_STATE_NORM) && valid && bad_exp_cmd) 1 -1" (3 "1101")
CHECKSUM: "3098039721 1365283866"
covergroup top_verichip7.verichip7.verichip7_cov::bus_interface
	coveritem "cx_cs_rw_add"
		bins {{"not_selected"},{"read","write"},{"alu","rgt","lft","con","cmd","sta","ver"}}
